### 1. 정차금지지대 수 격자화

In [1]:
# 가져다 쓸 모듈들
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns # 예쁜 matplotlib
import folium # 지도 시각화
import json # geojson 파일용
import geopandas as gpd # geojson 파일용

/opt/app-root/lib/python3.6/site-packages/geopandas/_compat.py:91: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string

In [2]:
filename = "30.대전광역시_차량등록현황_격자.geojson"
file = open(filename,encoding="utf8")
df90 = gpd.read_file(file)
df90

            gid  cars_cnt                                           geometry
0      다마846996         0  MULTIPOLYGON (((127.32871 36.19342, 127.32871 ...
1      다마847995         0  MULTIPOLYGON (((127.32983 36.19252, 127.32982 ...
2      다마847996         0  MULTIPOLYGON (((127.32982 36.19342, 127.32982 ...
3      다마847997         0  MULTIPOLYGON (((127.32982 36.19432, 127.32982 ...
4      다마847998         0  MULTIPOLYGON (((127.32982 36.19522, 127.32982 ...
...         ...       ...                                                ...
54907  라바052223         0  MULTIPOLYGON (((127.55799 36.39818, 127.55799 ...
54908  라바052224         0  MULTIPOLYGON (((127.55799 36.39908, 127.55799 ...
54909  라바053222         0  MULTIPOLYGON (((127.55910 36.39727, 127.55910 ...
54910  라바053223         0  MULTIPOLYGON (((127.55910 36.39818, 127.55910 ...
54911  라바053224         0  MULTIPOLYGON (((127.55910 36.39908, 127.55911 ...

[54912 rows x 3 columns]

In [3]:
df91=df90.copy()
df91

            gid  cars_cnt                                           geometry
0      다마846996         0  MULTIPOLYGON (((127.32871 36.19342, 127.32871 ...
1      다마847995         0  MULTIPOLYGON (((127.32983 36.19252, 127.32982 ...
2      다마847996         0  MULTIPOLYGON (((127.32982 36.19342, 127.32982 ...
3      다마847997         0  MULTIPOLYGON (((127.32982 36.19432, 127.32982 ...
4      다마847998         0  MULTIPOLYGON (((127.32982 36.19522, 127.32982 ...
...         ...       ...                                                ...
54907  라바052223         0  MULTIPOLYGON (((127.55799 36.39818, 127.55799 ...
54908  라바052224         0  MULTIPOLYGON (((127.55799 36.39908, 127.55799 ...
54909  라바053222         0  MULTIPOLYGON (((127.55910 36.39727, 127.55910 ...
54910  라바053223         0  MULTIPOLYGON (((127.55910 36.39818, 127.55910 ...
54911  라바053224         0  MULTIPOLYGON (((127.55910 36.39908, 127.55911 ...

[54912 rows x 3 columns]

In [4]:
df91['중앙분리대 비율']=0
df91

,gid,cars_cnt,geometry,중앙분리대 비율
0,다마846996,0,"MULTIPOLYGON (((127.32871 36.19342, 127.32871 ...",0
1,다마847995,0,"MULTIPOLYGON (((127.32983 36.19252, 127.32982 ...",0
2,다마847996,0,"MULTIPOLYGON (((127.32982 36.19342, 127.32982 ...",0
3,다마847997,0,"MULTIPOLYGON (((127.32982 36.19432, 127.32982 ...",0
4,다마847998,0,"MULTIPOLYGON (((127.32982 36.19522, 127.32982 ...",0
...,...,...,...,...
54907,라바052223,0,"MULTIPOLYGON (((127.55799 36.39818, 127.55799 ...",0
54908,라바052224,0,"MULTIPOLYGON (((127.55799 36.39908, 127.55799 ...",0
54909,라바053222,0,"MULTIPOLYGON (((127.55910 36.39727, 127.55910 ...",0
54910,라바053223,0,"MULTIPOLYGON (((127.55910 36.39818, 127.55910 ...",0
54911,라바053224,0,"MULTIPOLYGON (((127.55910 36.39908, 127.55911 ...",0

In [5]:
filename = "31.대전시_중앙분리대.geojson"
file = open(filename,encoding="utf8")
df = gpd.read_file(file)
df

,byc_len,byc_wid,std_hit,geometry
0,9.03,0.1,1.0,"MULTIPOLYGON (((127.35022 36.33998, 127.35022 ..."
1,18.13,0.1,1.0,"MULTIPOLYGON (((127.34994 36.31754, 127.34994 ..."
2,33.84,0.1,1.0,"MULTIPOLYGON (((127.34853 36.31767, 127.34853 ..."
3,33.84,0.1,1.0,"MULTIPOLYGON (((127.34931 36.31778, 127.34931 ..."
4,33.85,0.1,1.0,"MULTIPOLYGON (((127.35010 36.31790, 127.35010 ..."
5,99.20,0.1,1.0,"MULTIPOLYGON (((127.34843 36.32088, 127.34843 ..."
6,56.45,0.1,1.0,"MULTIPOLYGON (((127.35028 36.32563, 127.35028 ..."
7,117.31,0.1,1.0,"MULTIPOLYGON (((127.34848 36.32563, 127.34848 ..."
8,45.15,0.1,1.0,"MULTIPOLYGON (((127.35007 36.33976, 127.35007 ..."
9,29.30,0.1,1.0,"MULTIPOLYGON (((127.34973 36.34066, 127.34989 ..."
10,82.51,0.1,1.0,"MULTIPOLYGON (((127.35104 36.34074, 127.35104 ..."
11,87.16,0.1,1.0,"MULTIPOLYGON (((127.34894 36.33972, 127.34894 ..."
12,11.31,0.1,1.0,"MULTIPOLYGON (((127.35003 36.32588, 127.35003 ..."
13,68.41,0.3,1.0,"MULTIPOLYGON (((127.43619 36.33826, 127.43622 ..."
14,202.50,0.3,1.0,"MULTIPOLYGON (((127.43707 36.33484, 127.43707 ..."
15,64.38,0.2,1.2,"MULTIPOLYGON (((127.37442 36.37203, 127.37441 ..."

In [ ]:
print(len(df91))
for i in range (len(df91['geometry'])):
    print(i)
    for j in range (len(df['geometry'])):
        if df91['geometry'][i].intersects(df['geometry'][j])==True:
            df91['중앙분리대 수'][i]+=1
df91

In [ ]:
df91.to_file("격자_11-중앙분리대-1", driver="GeoJSON")

### 2. 정차금지지대 면적 격자화

In [9]:
filename = "격자_11-중앙분리대-1.json"
file = open(filename,encoding="utf8")
df90 = gpd.read_file(file)
df90['중앙분리대 면적']=0.0
df90=df90.reset_index()
df90

,index,gid,cars_cnt,중앙분리대 수,geometry,중앙분리대 면적
0,0,다마846996,0,0,"MULTIPOLYGON (((127.32871 36.19342, 127.32871 ...",0.0
1,1,다마847995,0,0,"MULTIPOLYGON (((127.32983 36.19252, 127.32982 ...",0.0
2,2,다마847996,0,0,"MULTIPOLYGON (((127.32982 36.19342, 127.32982 ...",0.0
3,3,다마847997,0,0,"MULTIPOLYGON (((127.32982 36.19432, 127.32982 ...",0.0
4,4,다마847998,0,0,"MULTIPOLYGON (((127.32982 36.19522, 127.32982 ...",0.0
...,...,...,...,...,...,...
54907,54907,라바052223,0,0,"MULTIPOLYGON (((127.55799 36.39818, 127.55799 ...",0.0
54908,54908,라바052224,0,0,"MULTIPOLYGON (((127.55799 36.39908, 127.55799 ...",0.0
54909,54909,라바053222,0,0,"MULTIPOLYGON (((127.55910 36.39727, 127.55910 ...",0.0
54910,54910,라바053223,0,0,"MULTIPOLYGON (((127.55910 36.39818, 127.55910 ...",0.0
54911,54911,라바053224,0,0,"MULTIPOLYGON (((127.55910 36.39908, 127.55911 ...",0.0

In [11]:
df91=df90.copy()
df91

,index,gid,cars_cnt,중앙분리대 수,geometry,중앙분리대 면적
0,0,다마846996,0,0,"MULTIPOLYGON (((127.32871 36.19342, 127.32871 ...",0.0
1,1,다마847995,0,0,"MULTIPOLYGON (((127.32983 36.19252, 127.32982 ...",0.0
2,2,다마847996,0,0,"MULTIPOLYGON (((127.32982 36.19342, 127.32982 ...",0.0
3,3,다마847997,0,0,"MULTIPOLYGON (((127.32982 36.19432, 127.32982 ...",0.0
4,4,다마847998,0,0,"MULTIPOLYGON (((127.32982 36.19522, 127.32982 ...",0.0
...,...,...,...,...,...,...
54907,54907,라바052223,0,0,"MULTIPOLYGON (((127.55799 36.39818, 127.55799 ...",0.0
54908,54908,라바052224,0,0,"MULTIPOLYGON (((127.55799 36.39908, 127.55799 ...",0.0
54909,54909,라바053222,0,0,"MULTIPOLYGON (((127.55910 36.39727, 127.55910 ...",0.0
54910,54910,라바053223,0,0,"MULTIPOLYGON (((127.55910 36.39818, 127.55910 ...",0.0
54911,54911,라바053224,0,0,"MULTIPOLYGON (((127.55910 36.39908, 127.55911 ...",0.0

In [12]:
filename = "31.대전시_중앙분리대.geojson"
file = open(filename,encoding="utf8")
df = gpd.read_file(file)
df

,byc_len,byc_wid,std_hit,geometry
0,9.03,0.1,1.0,"MULTIPOLYGON (((127.35022 36.33998, 127.35022 ..."
1,18.13,0.1,1.0,"MULTIPOLYGON (((127.34994 36.31754, 127.34994 ..."
2,33.84,0.1,1.0,"MULTIPOLYGON (((127.34853 36.31767, 127.34853 ..."
3,33.84,0.1,1.0,"MULTIPOLYGON (((127.34931 36.31778, 127.34931 ..."
4,33.85,0.1,1.0,"MULTIPOLYGON (((127.35010 36.31790, 127.35010 ..."
5,99.20,0.1,1.0,"MULTIPOLYGON (((127.34843 36.32088, 127.34843 ..."
6,56.45,0.1,1.0,"MULTIPOLYGON (((127.35028 36.32563, 127.35028 ..."
7,117.31,0.1,1.0,"MULTIPOLYGON (((127.34848 36.32563, 127.34848 ..."
8,45.15,0.1,1.0,"MULTIPOLYGON (((127.35007 36.33976, 127.35007 ..."
9,29.30,0.1,1.0,"MULTIPOLYGON (((127.34973 36.34066, 127.34989 ..."
10,82.51,0.1,1.0,"MULTIPOLYGON (((127.35104 36.34074, 127.35104 ..."
11,87.16,0.1,1.0,"MULTIPOLYGON (((127.34894 36.33972, 127.34894 ..."
12,11.31,0.1,1.0,"MULTIPOLYGON (((127.35003 36.32588, 127.35003 ..."
13,68.41,0.3,1.0,"MULTIPOLYGON (((127.43619 36.33826, 127.43622 ..."
14,202.50,0.3,1.0,"MULTIPOLYGON (((127.43707 36.33484, 127.43707 ..."
15,64.38,0.2,1.2,"MULTIPOLYGON (((127.37442 36.37203, 127.37441 ..."

In [13]:
t=gpd.overlay(df90,df,how='intersection')
t=t.reset_index()
t

,level_0,index,gid,cars_cnt,중앙분리대 수,중앙분리대 면적,byc_len,byc_wid,std_hit,geometry
0,0,16136,다바863137,0,1,0.0,99.20,0.1,1.0,"POLYGON ((127.34843 36.32089, 127.34849 36.320..."
1,1,16403,다바864137,0,1,0.0,99.20,0.1,1.0,"POLYGON ((127.34849 36.32089, 127.34953 36.320..."
2,2,16399,다바864133,0,2,0.0,33.84,0.1,1.0,"POLYGON ((127.34853 36.31767, 127.34890 36.317..."
3,3,16399,다바864133,0,2,0.0,33.84,0.1,1.0,"POLYGON ((127.34931 36.31778, 127.34961 36.317..."
4,4,16665,다바865133,0,2,0.0,33.84,0.1,1.0,"POLYGON ((127.34961 36.31783, 127.34968 36.317..."
5,5,16408,다바864142,0,1,0.0,117.31,0.1,1.0,"POLYGON ((127.34848 36.32563, 127.34918 36.325..."
6,6,16674,다바865142,0,3,0.0,117.31,0.1,1.0,"POLYGON ((127.34959 36.32565, 127.34978 36.325..."
7,7,16424,다바864158,0,1,0.0,87.16,0.1,1.0,"POLYGON ((127.34894 36.33972, 127.34956 36.340..."
8,8,16690,다바865158,0,4,0.0,87.16,0.1,1.0,"POLYGON ((127.34956 36.34002, 127.34978 36.340..."
9,9,16665,다바865133,0,2,0.0,18.13,0.1,1.0,"POLYGON ((127.34994 36.31754, 127.34993 36.317..."
10,10,16666,다바865134,0,1,0.0,33.85,0.1,1.0,"POLYGON ((127.35010 36.31790, 127.35047 36.317..."
11,11,16674,다바865142,0,3,0.0,56.45,0.1,1.0,"POLYGON ((127.35028 36.32564, 127.35040 36.325..."
12,12,16940,다바866142,0,1,0.0,56.45,0.1,1.0,"POLYGON ((127.35071 36.32565, 127.35091 36.325..."
13,13,16674,다바865142,0,3,0.0,11.31,0.1,1.0,"POLYGON ((127.35003 36.32588, 127.35003 36.325..."
14,14,16690,다바865158,0,4,0.0,9.03,0.1,1.0,"POLYGON ((127.35022 36.33998, 127.35017 36.340..."
15,15,16690,다바865158,0,4,0.0,45.15,0.1,1.0,"POLYGON ((127.35007 36.33976, 127.34963 36.339..."
16,16,16690,다바865158,0,4,0.0,82.51,0.1,1.0,"POLYGON ((127.35026 36.34034, 127.35026 36.340..."
17,17,16691,다바865159,0,2,0.0,82.51,0.1,1.0,"POLYGON ((127.35037 36.34040, 127.35041 36.340..."
18,18,16957,다바866159,0,1,0.0,82.51,0.1,1.0,"POLYGON ((127.35068 36.34055, 127.35077 36.340..."
19,19,16691,다바865159,0,2,0.0,29.30,0.1,1.0,"POLYGON ((127.34989 36.34044, 127.34989 36.340..."
20,20,22454,다바887194,0,1,0.0,64.38,0.2,1.2,"POLYGON ((127.37441 36.37204, 127.37453 36.372..."
21,21,37584,다바942154,29,1,0.0,202.50,0.3,1.0,"POLYGON ((127.43640 36.33634, 127.43632 36.336..."
22,22,37870,다바943152,8,1,0.0,202.50,0.3,1.0,"POLYGON ((127.43698 36.33507, 127.43707 36.334..."
23,23,37871,다바943153,10,1,0.0,202.50,0.3,1.0,"POLYGON ((127.43658 36.33597, 127.43659 36.335..."
24,24,37872,다바943154,18,1,0.0,202.50,0.3,1.0,"POLYGON ((127.43649 36.33616, 127.43654 36.336..."
25,25,37586,다바942156,19,1,0.0,68.41,0.3,1.0,"POLYGON ((127.43645 36.33828, 127.43644 36.338..."
26,26,37874,다바943156,5,1,0.0,68.41,0.3,1.0,"POLYGON ((127.43648 36.33829, 127.43649 36.338..."

In [14]:
for a,b in zip(t['index'].to_list(),t.area.to_list()):
    df91['중앙분리대 면적'][a]+=b

/opt/app-root/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  """Entry point for launching an IPython kernel.
/opt/app-root/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
df91[df91['중앙분리대 수']>0]

,index,gid,cars_cnt,중앙분리대 수,geometry,중앙분리대 면적
16136,16136,다바863137,0,1,"MULTIPOLYGON (((127.34737 36.32056, 127.34737 ...",5.476727e-11
16399,16399,다바864133,0,2,"MULTIPOLYGON (((127.34849 36.31696, 127.34849 ...",6.149465e-10
16403,16403,다바864137,0,1,"MULTIPOLYGON (((127.34849 36.32056, 127.34849 ...",9.407306e-10
16408,16408,다바864142,0,1,"MULTIPOLYGON (((127.34848 36.32507, 127.34848 ...",1.005460e-09
16424,16424,다바864158,0,1,"MULTIPOLYGON (((127.34845 36.33949, 127.34845 ...",6.532456e-10
16665,16665,다바865133,0,2,"MULTIPOLYGON (((127.34961 36.31696, 127.34961 ...",2.461001e-10
16666,16666,다바865134,0,1,"MULTIPOLYGON (((127.34961 36.31786, 127.34960 ...",3.397321e-10
16674,16674,다바865142,0,3,"MULTIPOLYGON (((127.34959 36.32507, 127.34959 ...",6.723376e-10
16690,16690,다바865158,0,4,"MULTIPOLYGON (((127.34957 36.33950, 127.34956 ...",8.805645e-10
16691,16691,다바865159,0,2,"MULTIPOLYGON (((127.34956 36.34040, 127.34956 ...",6.160191e-10
16940,16940,다바866142,0,1,"MULTIPOLYGON (((127.35071 36.32507, 127.35071 ...",1.795642e-10
16957,16957,다바866159,0,1,"MULTIPOLYGON (((127.35068 36.34040, 127.35068 ...",3.912763e-10
22454,22454,다바887194,0,1,"MULTIPOLYGON (((127.37403 36.37198, 127.37403 ...",1.292972e-09
37584,37584,다바942154,29,1,"MULTIPOLYGON (((127.43537 36.33597, 127.43537 ...",9.894977e-10
37586,37586,다바942156,19,1,"MULTIPOLYGON (((127.43537 36.33777, 127.43537 ...",1.327312e-09
37870,37870,다바943152,8,1,"MULTIPOLYGON (((127.43649 36.33416, 127.43649 ...",8.786021e-10
37871,37871,다바943153,10,1,"MULTIPOLYGON (((127.43649 36.33507, 127.43649 ...",3.141040e-09
37872,37872,다바943154,18,1,"MULTIPOLYGON (((127.43649 36.33597, 127.43649 ...",6.086978e-10
37874,37874,다바943156,5,1,"MULTIPOLYGON (((127.43648 36.33777, 127.43648 ...",2.085631e-09

In [17]:
df91.to_file("격자_11-중앙분리대-2", driver="GeoJSON")